name: Headless Acceptance Tests

on: push

jobs:
  headless-acceptance-tests:
    name: Chrome Acceptance Tests (Headless)
    runs-on: ubuntu-latest
    env: 
      MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run setup-test-site
      - run: npm run build-test-site
      - name: Run Acceptance Tests
        run: npm run acceptance -- --browsers chrome:headless
