# This workflow will run our tests, generate an lcov code coverage file,
# and send that coverage to Coveralls 

name: Code Coverage

on:
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  call_coveralls:
    uses: yext/slapshot-reusable-workflows/.github/workflows/coverage.yml@dev/percy-workflow-mapbox
    with:
      test_script: npx jest tests/static/ --coverage
      comparison_branch: master
    secrets:
      caller_github_token: ${{ secrets.GITHUB_TOKEN }}
